-- Database Setup --
--------------------

CREATE USER IF NOT EXISTS '$DB_USERNAME'@'$DB_HOST' IDENTIFIED BY '$DB_PASSWORD';
CREATE DATABASE IF NOT EXISTS $DB_DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON $DB_DATABASE.* TO '$DB_USERNAME'@'$DB_HOST';
FLUSH PRIVILEGES;


-- Verification --
------------------
SELECT user, host FROM mysql.user WHERE user = '$DB_USERNAME';
SHOW GRANTS FOR '$DB_USERNAME'@'$DB_HOST';
SHOW DATABASES WHERE Database = '$DB_DATABASE';

